import sys
import typing as t

import requests

from billmgr import logger as logging
import payment  # TODO: заимпортить всё нормально
from customtinkoffpayment.paymentcgi import PaymentCgi
from customtinkoffpayment.tinkoffkassa import TinkoffKassa


MODULE = 'payment'

logging.init_logging('testpayment')
logger = logging.get_logger('testpayment')


class TinkoffPaymentCgi(PaymentCgi):

    def __init__(self):
        super().__init__()

        self.int_amount = self.payment_params.get("paymethodamount")\
                              .replace(".", "")
        self.order_id = "billmgr#{0}#{1}".format(
            self.elid, self.payment_params.get("randomnumber"))

    def process(self):
        # необходимые данные достаем из self.payment_params, self.paymethod_params, self.user_params
        # здесь для примера выводим параметры метода оплаты (self.paymethod_params) и платежа (self.payment_params) в лог
        logger.info(f"paymethod_params = {self.paymethod_params}")
        logger.info(f"payment_params = {self.payment_params}")
        # Вывод:
        # ... paymethod_params = {'id': '2', 'orderpriority': '2', 'name': None, 'active': 'on', 'minamount': '1.00', 'maxamount': None, 'autoclearperiod': None, 'currency': '126', 'profiletype': '1,2,3', 'commissionamount': '0.00', 'commissionpercent': '0', 'module': 'pmtestpayment', 'doctmpl': None, 'recurring': 'off', 'numtmpl_payment': None, 'nextnum_payment': None, 'payimage': None, 'payimagenewface': None, 'allowrefund': 'off', 'language': None, 'payment_description': None, 'note': None, 'description': None, 'receipt_profiletype': None, 'description_markdown': None, 'successpage': None, 'failpage': None, 'pendingpage': None, 'successpage_recurring': None, 'failpage_recurring': None, 'pendingpage_recurring': None, 'successpage_subscription': None, 'failpage_subscription': None, 'pendingpage_subscription': None, 'verified': 'off', 'name_ru': 'перв тест', 'description_ru': None, 'description_markdown_ru': None, 'terminalkey': 'lll', 'terminalpsw': 'ppp'}
        # ... payment_params = {'id': '2', 'subaccount': '1', 'paymethod': None, 'recipient': None, 'sender': None, 'subaccountamount': '1.00', 'status': '8', 'number': 'pfx/2', 'paymethodamount': '1.00', 'usedamount': '0.00', 'commissionamount': '0.00', 'expense_commission': None, 'paydate': None, 'createdate': '2024-04-30 15:28:52', 'taxrate': None, 'taxamount': None, 'currency': None, 'externalid': None, 'billorder': None, 'recurring': None, 'recurring_subscription': None, 'documentnumber': None, 'randomnumber': '15ajF8ZjxBn5', 'documentdate': None, 'description': 'Авансовый платеж #2', 'invoice': None, 'refund': 'off', 'restrictrefund': 'off', 'recurring_action_on_fail': None, 'recurring_action_on_success': None, 'autogenerated': 'off', 'chargecommission': 'on', 'paymethodcommissionamount': '0.00', 'remote_ip': '192.168.60.90', 'manager_url': 'https://192.168.40.66/billmgr', 'user_id': '1', 'useremail': '342848h8942h3@fhdgdfv89h3.ru', 'userrealname': '342848h8942h3@fhdgdfv89h3.ru', 'userphone': None, 'project': None, 'items': None, 'notaxamount': '1.00', 'no_vat': 'off'}

        request_body: dict[t.Union[str, int]] = {
            "TerminalKey": self.paymethod_params.get("terminalkey"),  # TODO
            "Amount": self.int_amount,
            "OrderId": self.order_id,
            "SuccessURL": self.success_page + "&elid=" + self.elid + "&module=" + "testpayment",  # TODO заменить &module имя
            "FailURL": self.fail_page + "&elid=" + self.elid+"&module=" + "testpayment",
        }
        request_body.update({"Token": generate_token(
            request_body, password=self.paymethod_params.get("terminalpsw"))})  # TODO
        logger.info(f"request_body = {request_body}")
        kassa_url: str = "https://securepay.tinkoff.ru/v2/Init"
        kassa_response: dict[t.Union[str, int]] = requests\
            .post(url=kassa_url, json=request_body)\
            .json()
        logger.info("kassa_response = " + str(kassa_response))

        kassa_info: str = "{0} {1}".format(kassa_response.get("Message"),
                                           kassa_response.get("Details"))
        if not kassa_response.get("Success"):
            payment.set_canceled(payment_id=self.elid,
                                 info=kassa_info,
                                 externalid=kassa_response.get("PaymentId"))
            raise Exception("Ошибка инициализации платежа")

        # переводим платеж в статус оплачивается
        payment.set_in_pay(payment_id=self.elid,
                           info="",
                           externalid=kassa_response.get("PaymentId"))
        # payment.set_in_pay(self.elid, '', 'external_' + self.elid)

        # url для перенаправления c cgi
        # здесь, в тестовом примере сразу перенаправляем на страницу BILLmanager
        # должны перенаправлять на страницу платежной системы
        # redirect_url = self.pending_page
        redirect_url: str = kassa_response.get("PaymentURL")

        # формируем html и отправляем в stdout
        # таким образом переходим на redirect_url
        # TODO: загрузить http из templates, заменить "{{ redirect_url }}" и записать в переменную
        payment_form: str = '<html>\n<head>\n<meta http-equiv="refresh" content="0; URL={0}">\n</head>\n<body></body>\n</html>'\
            .format(redirect_url)

        sys.stdout.write(payment_form)
